/**
 *  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class Problem002 {


	public static void main (String ... args) {
		
		long sum = 0;

		int previous = 1;
		int current = 2;
		while (current < 4000000) {
			int temp = current;
			current += previous;
			previous = temp;

			if (previous % 2 == 0) {
				sum += previous;
			}
		}

		System.out.println("sum : " + sum );
	}
}
